#!/usr/bin/env zsh
DOTFILES="/home/ofk/.dotfiles"
STOW_FOLDERS=(i3 neofetch polybar zsh)
pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
